import re
import logging
from typing import List, Dict, Any, Optional
from app.db import repositories

logger = logging.getLogger("case_studio.decision_gate")

# Regex to detect [DECISION_GATE] blocks in LLM outputs
GATE_PATTERN = re.compile(
    r"\[DECISION_GATE\]\s*(?:Thema|Topic):\s*(?P<topic>[^\n]+)\s*(?:Fehlender Fakt|Missing Fact):\s*(?P<fact>[^\n]+)\s*(?:Empfohlene Rueckfrage|Empfohlene Rückfrage|Recommended Question):\s*(?P<question>[^\n]+)\s*\[/DECISION_GATE\]",
    re.IGNORECASE | re.MULTILINE
)


def extract_decision_gates_from_text(text: str) -> List[Dict[str, str]]:
    """Extracts structured decision gates generated by the Master-Consultant prompt."""
    gates = []
    for match in GATE_PATTERN.finditer(text):
        gates.append({
            "topic": match.group("topic").strip(),
            "detected_missing_fact": match.group("fact").strip(),
            "recommended_question": match.group("question").strip()
        })
    return gates


async def record_detected_gates(session_id: str, text: str) -> List[Dict[str, Any]]:
    """Finds decision gates in response and persists them into SQLite decision_gates table."""
    detected = extract_decision_gates_from_text(text)
    saved_gates = []
    for g in detected:
        # Check if identical pending gate already exists for this session
        existing = await repositories.list_decision_gates(session_id)
        if any(e["topic"].lower() == g["topic"].lower() and e["status"] == "pending" for e in existing):
            continue
            
        gate = await repositories.create_decision_gate(
            session_id=session_id,
            topic=g["topic"],
            detected_missing_fact=g["detected_missing_fact"],
            recommended_question=g["recommended_question"],
            status="pending"
        )
        saved_gates.append(gate)
        logger.info(f"Recorded new Decision Gate for session {session_id}: {g['topic']}")
    return saved_gates


def extract_mermaid_from_text(text: str) -> Optional[str]:
    """Extracts Mermaid graph definition from code blocks."""
    match = re.search(r"```mermaid\s*\n([\s\S]*?)\n```", text, re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return None
