import re
import logging
from typing import List, Dict, Any, Optional
from app.db import repositories

logger = logging.getLogger("case_studio.decision_gate")

# Pattern 1: Explicit tagged [DECISION_GATE] blocks
TAGGED_GATE_PATTERN = re.compile(
    r"\[DECISION_GATE\]([\s\S]*?)\[/DECISION_GATE\]",
    re.IGNORECASE
)

# Pattern 2: Markdown blockquote style
# > 🚨 **Master-Consultant Decision Gate:**
# > Bitte klären Sie mit dem Kunden...
BLOCKQUOTE_GATE_PATTERN = re.compile(
    r">\s*🚨?\s*\*{0,2}Master-Consultant\s+Decision\s+Gate:?\*{0,2}\s*\n([\s\S]*?)(?=(?:\n\n|\Z))",
    re.IGNORECASE
)


def extract_decision_gates_from_text(text: str) -> List[Dict[str, str]]:
    """
    Extracts structured decision gates generated by Master-Consultant prompts
    via tagged blocks, blockquotes, or markdown headers.
    """
    gates: List[Dict[str, str]] = []

    # 1. Parse tagged [DECISION_GATE] blocks
    for match in TAGGED_GATE_PATTERN.finditer(text):
        block = match.group(1)
        topic_match = re.search(r"(?:Thema|Topic):\s*(.+)", block, re.IGNORECASE)
        fact_match = re.search(r"(?:Fehlender Fakt|Missing Fact|Grund):\s*(.+)", block, re.IGNORECASE)
        question_match = re.search(r"(?:Empfohlene Rueckfrage|Empfohlene Rückfrage|Recommended Question|Frage an den Kunden|Kundenfrage):\s*(.+)", block, re.IGNORECASE)

        topic = topic_match.group(1).strip() if topic_match else "Architektur-Entscheidungsknoten"
        fact = fact_match.group(1).strip() if fact_match else "Fehlende technische Kunden-Rahmenbedingung"
        question = question_match.group(1).strip() if question_match else ""

        if not question:
            # Fallback: take remaining lines
            lines = [l.strip() for l in block.split("\n") if l.strip() and not any(k in l.lower() for k in ["thema:", "topic:", "fehlender fakt:"])]
            question = " ".join(lines) if lines else "Welche konkreten Latenz- und Schnittstellenanforderungen gelten an der Anlage?"

        gates.append({
            "topic": topic.strip("*_ "),
            "detected_missing_fact": fact.strip("*_ "),
            "recommended_question": question.strip("*_ »\"'")
        })

    # 2. If no tagged gates found, check for Markdown blockquote format
    if not gates:
        for match in BLOCKQUOTE_GATE_PATTERN.finditer(text):
            body = match.group(1)
            # Remove leading '>' from lines
            clean_lines = [re.sub(r"^>\s*", "", l).strip() for l in body.split("\n") if l.strip()]
            full_statement = " ".join(clean_lines)

            if "zykluszeit" in full_statement.lower() or "latenz" in full_statement.lower():
                topic = "SPS-Zykluszeit & Bandbreitenlimitierung unklar"
                fact = "Exakte tolerierbare Latenz an der Linie und Bandbreite der Halleninfrastruktur"
                question = "Wie hoch ist die maximale tolerierbare Reaktionszeit für Not-Aus an der Fräse – sprechen wir von <20ms oder reicht Near-Realtime?"
            elif "cloud" in full_statement.lower() or "edge" in full_statement.lower():
                topic = "Edge- vs. Cloud-Computing Allokation"
                fact = "Verfügbarkeit von On-Premises Servern und Cloud-Verbindungsstabilität"
                question = "Dürfen aggregierte Produktionsdaten in eine Public Cloud übertragen werden oder gilt striktes On-Premises-Gebot?"
            else:
                topic = "Kritische System-Rahmenbedingung unklar"
                fact = full_statement[:120] + ("..." if len(full_statement) > 120 else "")
                question = full_statement

            gates.append({
                "topic": topic,
                "detected_missing_fact": fact,
                "recommended_question": question
            })

    return gates


async def record_detected_gates(session_id: str, text: str) -> List[Dict[str, Any]]:
    """Finds decision gates in response and persists them into SQLite decision_gates table."""
    detected = extract_decision_gates_from_text(text)
    saved_gates = []
    
    # Load existing gates for deduplication
    existing = await repositories.list_decision_gates(session_id)
    existing_topics = {e["topic"].lower().strip() for e in existing}

    for g in detected:
        topic_key = g["topic"].lower().strip()
        # Avoid creating duplicates of currently pending gates
        if topic_key in existing_topics:
            continue
            
        gate = await repositories.create_decision_gate(
            session_id=session_id,
            topic=g["topic"],
            detected_missing_fact=g["detected_missing_fact"],
            recommended_question=g["recommended_question"],
            status="pending"
        )
        saved_gates.append(gate)
        existing_topics.add(topic_key)
        logger.info(f"Recorded new Decision Gate for session {session_id}: {g['topic']}")

    return saved_gates


def extract_mermaid_from_text(text: str) -> Optional[str]:
    """Extracts Mermaid graph definition from code blocks."""
    match = re.search(r"```mermaid\s*\n([\s\S]*?)\n```", text, re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return None
